version: "3.9"

services:
  db:
    image: postgres:16.1-bullseye
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=book_store_user
      - POSTGRES_PASSWORD=book_store_password
      - POSTGRES_DB=book_store_db
    ports:
      - "5432:5432"


volumes:
  postgres_data: