# Generated by Django 4.2 on 2023-12-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='my_category'),
            preserve_default=False,
        ),
    ]
