# Generated by Django 4.2 on 2023-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
